# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Role.delete_all
Role.create(:code=>'ADM', :name=>'Admin')
Role.create(:code=>'ATT', :name=>'Attendance')
Role.create(:code=>'DNR', :name=>'Dinner')
Role.create(:code=>'HTL', :name=>'Admin Hotel')
Role.create(:code=>'LGS', :name=>'Admin Logistic')
Role.create(:code=>'USH', :name=>'Admin Ushrer')
Role.create(:code=>'APT', :name=>'Admin Airport')
Role.create(:code=>'DLG', :name=>'Admin Participant')
Role.create(:code=>'SPK', :name=>'Admin Speaker')
Role.create(:code=>'MDA', :name=>'Admin Media')
Role.create(:code=>'PLS', :name=>'Admin Polis')


User.delete_all
User.create(:username=>'adminGES', :role_code=>'ADM', :usefor=>'system', :password=>'$2a$10$qKRzjhOFvEE5u8H4UqBxJet4xGEQIvx4HiOOaNyF2NN54R0Zjf3BK', :password_salt=>'$2a$10$qKRzjhOFvEE5u8H4UqBxJe')
User.create(:username=>'attendance', :role_code=>'ATT', :usefor=>'attendance', :password=>'$2a$10$a49gi6O71PFBz/rfD/Jfl.ZbNFNcNuspT/gOk9VF9crzfujGJ36le', :password_salt=>'$2a$10$a49gi6O71PFBz/rfD/Jfl.')
User.create(:username=>'hotel', :role_code=>'HTL', :usefor=>'notification', :password=>'$2a$10$uHxUoaYpimjZcMznwbTA7uiXFbppBZ6ufDOvFdcJU8zQQ6nwGW56O', :password_salt=>'$2a$10$uHxUoaYpimjZcMznwbTA7u')
User.create(:username=>'transport', :role_code=>'LGS', :usefor=>'notification', :password=>'$2a$10$Zd8ZTHGCLPyWVKV4HnDdkeDsWY9QsOqBQOKcLONK6IqyW.TC4/NjS', :password_salt=>'$2a$10$Zd8ZTHGCLPyWVKV4HnDdke')
User.create(:username=>'ushered', :role_code=>'USH', :usefor=>'notification', :password=>'$2a$10$5tQUlkugccJ3NGeD7f7MQOOxy1sWXCp3OyFT8096llOOeRpOxDf2K', :password_salt=>'$2a$10$5tQUlkugccJ3NGeD7f7MQO')
User.create(:username=>'participant', :role_code=>'DLG', :usefor=>'system', :password=>'$2a$10$2rGUitMRUqbjYZsxQYKNpeBJ36Zr48w2S7aFPgwvuvttK94WvusLO', :password_salt=>'$2a$10$2rGUitMRUqbjYZsxQYKNpe')
User.create(:username=>'speaker', :role_code=>'SPK', :usefor=>'system', :password=>'$2a$10$mEE5pSGqAKg5R4.z1ms.CepUQO9mWD48h8M7L0T57xPqDf7Aqs1Na', :password_salt=>'$2a$10$mEE5pSGqAKg5R4.z1ms.Ce')
User.create(:username=>'media', :role_code=>'MDA', :usefor=>'system', :password=>'$2a$10$rQpq9O/bDDWPMDlDLuFCheUFpx3Q.Hst8wxYGkYUBXv4n2Q7cTBBy', :password_salt=>'$2a$10$rQpq9O/bDDWPMDlDLuFChe')
User.create(:username=>'airport', :role_code=>'APT', :usefor=>'notification', :password=>'$2a$10$c8wtZ/KsMfdbylDvUrlE7.3wn1aA1lvPuPwu0zpv6co9I/euBIDEK', :password_salt=>'$2a$10$c8wtZ/KsMfdbylDvUrlE7.')
User.create(:username=>'hotel2', :role_code=>'HTL', :usefor=>'notification', :password=>'$2a$10$vq63ZRp5jgMn/jV9eyhdH.ATl9No/VOj/7h2NpVoX/919Ab/WdUo2', :password_salt=>'$2a$10$vq63ZRp5jgMn/jV9eyhdH.')
User.create(:username=>'polis', :role_code=>'PLS', :usefor=>'notification', :password=>'$2a$10$HknLrqdMwxXRLXL30fYUEOd3NTZDCsPhrwu3b0QW.GvfgvbKUfmYy', :password_salt=>'$2a$10$HknLrqdMwxXRLXL30fYUEO')
			


Notifystatus.delete_all
Notifystatus.create(:code=>'NO', :name=>'Not Notify')
Notifystatus.create(:code=>'PE', :name=>'Pending Notification')
Notifystatus.create(:code=>'ACK', :name=>'Acknowledged')


Trackstatus.delete_all
Trackstatus.create(:code=>'ACT', :name=>'Active')
Trackstatus.create(:code=>'INA', :name=>'Inactive')


Tracktype.delete_all
Tracktype.create(:code=>'PLN', :name=>'Plenary')
Tracktype.create(:code=>'PRL', :name=>'Parallel')
Tracktype.create(:code=>'DNR', :name=>'Dinner')

Participanttype.delete_all
Participanttype.create(:code=>'DLG', :name=>'Participant')
Participanttype.create(:code=>'MDA', :name=>'Staff')
Participanttype.create(:code=>'SPK', :name=>'Speaker')


Room.delete_all
Room.create(:code=>'PHG', :name=>'Pahang', :capacity => 100, :current => 0, :img => 'pahang.png')
Room.create(:code=>'SLG', :name=>'Selangor', :capacity => 100, :current => 0, :img => 'selangor.png')
Room.create(:code=>'JHR', :name=>'Johor', :capacity => 100, :current => 0, :img => 'johor.png')
Room.create(:code=>'PRK', :name=>'Perak', :capacity => 100, :current => 0, :img => 'perak.png')
Room.create(:code=>'KDH', :name=>'Kedah', :capacity => 100, :current => 0, :img => 'kedah.png')
Room.create(:code=>'PNG', :name=>'Penang', :capacity => 100, :current => 0, :img => 'penang.png')
Room.create(:code=>'SBH', :name=>'Sabah', :capacity => 100, :current => 0, :img => 'sabah.png')
Room.create(:code=>'SRK', :name=>'Sarawak', :capacity => 100, :current => 0, :img => 'sarawak.png')


Registrationstatus.delete_all
Registrationstatus.create(:code=>'PR', :name=>'Pre-registered')
Registrationstatus.create(:code=>'QU', :name=>'Queue')
Registrationstatus.create(:code=>'ACT', :name=>'Activated')


Trackrole.delete_all
Trackrole.create(:code=>'MDR', :name=>'Moderator')
Trackrole.create(:code=>'SPK', :name=>'Speaker')


Slot.delete_all
Slot.create(:code=>'SL1', :name=>'Slot 1', :start=> "09:00:00 AM", :end=> "10:30:00 AM")
Slot.create(:code=>'SL2', :name=>'Slot 2', :start=> "11:00:00 AM", :end=> "12:30:00 PM")
Slot.create(:code=>'SL3', :name=>'Slot 3', :start=> "14:00:00 PM", :end=> "15:30:00 PM")
Slot.create(:code=>'SL4', :name=>'Slot 4', :start=> "16:00:00 PM", :end=> "17:30:00 PM")
Slot.create(:code=>'SL5', :name=>'Slot 5', :start=> "18:00:00 PM", :end=> "19:30:00 PM")
Slot.create(:code=>'SL6', :name=>'Slot 6', :start=> "20:00:00 PM", :end=> "22:00:00 PM")
Slot.create(:code=>'SL7', :name=>'Slot 7', :start=> "22:00:00 PM", :end=> "24:00:00 AM")


Pollstatus.delete_all
Pollstatus.create(:code=>'ACT', :name=>'Active')
Pollstatus.create(:code=>'INA', :name=>'Inactive')


Hotel.delete_all
Hotel.create(:code=>'TDKL', :name=>'TRADERS HOTEL KUALA LUMPUR', :phone=> '03-23329888')
Hotel.create(:code=>'RKLH', :name=>'RENAISSANCE KUALA LUMPUR HOTEL', :phone=> '03-21622233')
Hotel.create(:code=>'IKHSKL', :name=>'IMPIANA KLCC HOTEL & SPA KUALA LUMPUR', :phone=> '03-21471111')
Hotel.create(:code=>'GYKLH', :name=>'GRAND YATT KUALA LUMPUR HOTEL', :phone=> '03-21821234')
Hotel.create(:code=>'TRBKLH', :name=>'THE ROYAL BINTANG KUALA LUMPUR HOTEL', :phone=> '03-21439898')
Hotel.create(:code=>'RIHKL', :name=>'RADIUS INTERNATIONAL HOTEL KUALA LUMPUR', :phone=> '03-27153888')
Hotel.create(:code=>'CRSSKL', :name=>'CROWN REGENCY SERVICED SUITES KUALA LUMPUR', :phone=> '03-21623888')
Hotel.create(:code=>'SRLHKL', :name=>'SHANGRI-LA HOTEL KUALA LUMPUR', :phone=> '1300 88 7388')
Hotel.create(:code=>'OTH', :name=>'OTHERS', :phone=> '')


Nationality.delete_all
Nationality.create(:code=>"AFG", :name=>"AFGHANISTAN")
Nationality.create(:code=>"ALB", :name=>"ALBANIA")
Nationality.create(:code=>"DZA", :name=>"ALGERIA")
Nationality.create(:code=>"ASM", :name=>"AMERICAN SAMOA")
Nationality.create(:code=>"AND", :name=>"ANDORRA")
Nationality.create(:code=>"AGO", :name=>"ANGOLA")
Nationality.create(:code=>"AIA", :name=>"ANGUILLA")
Nationality.create(:code=>"ATA", :name=>"ANTARCTICA")
Nationality.create(:code=>"ATG", :name=>"ANTIGUA AND BARBUDA")
Nationality.create(:code=>"ARG", :name=>"ARGENTINA")
Nationality.create(:code=>"ARM", :name=>"ARMENIA")
Nationality.create(:code=>"ABW", :name=>"ARUBA")
Nationality.create(:code=>"AUS", :name=>"AUSTRALIA")
Nationality.create(:code=>"AUT", :name=>"AUSTRIA")
Nationality.create(:code=>"AZE", :name=>"AZERBAIJAN")
Nationality.create(:code=>"BHS", :name=>"BAHAMAS")
Nationality.create(:code=>"BHR", :name=>"BAHRAIN")
Nationality.create(:code=>"BGD", :name=>"BANGLADESH")
Nationality.create(:code=>"BRB", :name=>"BARBADOS")
Nationality.create(:code=>"BLR", :name=>"BELARUS")
Nationality.create(:code=>"BEL", :name=>"BELGIUM")
Nationality.create(:code=>"BLZ", :name=>"BELIZE")
Nationality.create(:code=>"BEN", :name=>"BENIN")
Nationality.create(:code=>"BMU", :name=>"BERMUDA")
Nationality.create(:code=>"BTN", :name=>"BHUTAN")
Nationality.create(:code=>"BOL", :name=>"BOLIVIA")
Nationality.create(:code=>"BIH", :name=>"BOSNIA AND HERZEGOWINA")
Nationality.create(:code=>"BWA", :name=>"BOTSWANA")
Nationality.create(:code=>"BVT", :name=>"BOUVET ISLAND")
Nationality.create(:code=>"BRA", :name=>"BRAZIL")
Nationality.create(:code=>"IOT", :name=>"BRITISH INDIAN OCEAN TERRITORY")
Nationality.create(:code=>"BRN", :name=>"BRUNEI DARUSSALAM")
Nationality.create(:code=>"BGR", :name=>"BULGARIA")
Nationality.create(:code=>"BFA", :name=>"BURKINA FASO")
Nationality.create(:code=>"BDI", :name=>"BURUNDI")
Nationality.create(:code=>"KHM", :name=>"CAMBODIA")
Nationality.create(:code=>"CMR", :name=>"CAMEROON")
Nationality.create(:code=>"CAN", :name=>"CANADA")
Nationality.create(:code=>"CPV", :name=>"CAPE VERDE")
Nationality.create(:code=>"CYM", :name=>"CAYMAN ISLANDS")
Nationality.create(:code=>"CAF", :name=>"CENTRAL AFRICAN REPUBLIC")
Nationality.create(:code=>"TCD", :name=>"CHAD")
Nationality.create(:code=>"CHL", :name=>"CHILE")
Nationality.create(:code=>"CHN", :name=>"CHINA")
Nationality.create(:code=>"CXR", :name=>"CHRISTMAS ISLAND")
Nationality.create(:code=>"CCK", :name=>"COCOS (KEELING) ISLANDS")
Nationality.create(:code=>"COL", :name=>"COLOMBIA")
Nationality.create(:code=>"COM", :name=>"COMOROS")
Nationality.create(:code=>"COG", :name=>"CONGO")
Nationality.create(:code=>"COD", :name=>"CONGO, THE DRC")
Nationality.create(:code=>"COK", :name=>"COOK ISLANDS")
Nationality.create(:code=>"CRI", :name=>"COSTA RICA")
Nationality.create(:code=>"CIV", :name=>"COTE D'IVOIRE")
Nationality.create(:code=>"HRV", :name=>"CROATIA (local name: Hrvatska)")
Nationality.create(:code=>"CUB", :name=>"CUBA")
Nationality.create(:code=>"CYP", :name=>"CYPRUS")
Nationality.create(:code=>"CZE", :name=>"CZECH REPUBLIC")
Nationality.create(:code=>"DNK", :name=>"DENMARK")
Nationality.create(:code=>"DJI", :name=>"DJIBOUTI")
Nationality.create(:code=>"DMA", :name=>"DOMINICA")
Nationality.create(:code=>"DOM", :name=>"DOMINICAN REPUBLIC")
Nationality.create(:code=>"TMP", :name=>"EAST TIMOR")
Nationality.create(:code=>"ECU", :name=>"ECUADOR")
Nationality.create(:code=>"EGY", :name=>"EGYPT")
Nationality.create(:code=>"SLV", :name=>"EL SALVADOR")
Nationality.create(:code=>"GNQ", :name=>"EQUATORIAL GUINEA")
Nationality.create(:code=>"ERI", :name=>"ERITREA")
Nationality.create(:code=>"EST", :name=>"ESTONIA")
Nationality.create(:code=>"ETH ", :name=>"ETHIOPIA")
Nationality.create(:code=>"FLK", :name=>"FALKLAND ISLANDS (MALVINAS)")
Nationality.create(:code=>"FRO", :name=>"FAROE ISLANDS")
Nationality.create(:code=>"FJI", :name=>"FIJI")
Nationality.create(:code=>"FIN", :name=>"FINLAND")
Nationality.create(:code=>"FRA", :name=>"FRANCE")
Nationality.create(:code=>"FXX", :name=>"FRANCE, METROPOLITAN")
Nationality.create(:code=>"GUF", :name=>"FRENCH GUIANA")
Nationality.create(:code=>"PYF", :name=>"FRENCH POLYNESIA")
Nationality.create(:code=>"ATF", :name=>"FRENCH SOUTHERN TERRITORIES")
Nationality.create(:code=>"GAB", :name=>"GABON")
Nationality.create(:code=>"GMB", :name=>"GAMBIA")
Nationality.create(:code=>"GEO", :name=>"GEORGIA")
Nationality.create(:code=>"DEU", :name=>"GERMANY")
Nationality.create(:code=>"GHA", :name=>"GHANA")
Nationality.create(:code=>"GIB", :name=>"GIBRALTAR")
Nationality.create(:code=>"GRC", :name=>"GREECE")
Nationality.create(:code=>"GRL", :name=>"GREENLAND")
Nationality.create(:code=>"GRD", :name=>"GRENADA")
Nationality.create(:code=>"GLP", :name=>"GUADELOUPE")
Nationality.create(:code=>"GUM", :name=>"GUAM")
Nationality.create(:code=>"GTM", :name=>"GUATEMALA")
Nationality.create(:code=>"GIN", :name=>"GUINEA")
Nationality.create(:code=>"GNB", :name=>"GUINEA-BISSAU")
Nationality.create(:code=>"GUY", :name=>"GUYANA")
Nationality.create(:code=>"HTI", :name=>"HAITI")
Nationality.create(:code=>"HMD", :name=>"HEARD AND MC DONALD ISLANDS")
Nationality.create(:code=>"VAT", :name=>"HOLY SEE (VATICAN CITY STATE)")
Nationality.create(:code=>"HND", :name=>"HONDURAS")
Nationality.create(:code=>"HKG", :name=>"HONG KONG")
Nationality.create(:code=>"HUN", :name=>"HUNGARY")
Nationality.create(:code=>"ISL", :name=>"ICELAND")
Nationality.create(:code=>"IND", :name=>"INDIA")
Nationality.create(:code=>"IDN", :name=>"INDONESIA")
Nationality.create(:code=>"IRN", :name=>"IRAN (ISLAMIC REPUBLIC OF)")
Nationality.create(:code=>"IRQ", :name=>"IRAQ")
Nationality.create(:code=>"IRL", :name=>"IRELAND")
Nationality.create(:code=>"ISR", :name=>"ISRAEL")
Nationality.create(:code=>"ITA", :name=>"ITALY")
Nationality.create(:code=>"JAM", :name=>"JAMAICA")
Nationality.create(:code=>"JPN", :name=>"JAPAN")
Nationality.create(:code=>"JOR", :name=>"JORDAN")
Nationality.create(:code=>"KAZ", :name=>"KAZAKHSTAN")
Nationality.create(:code=>"KEN", :name=>"KENYA")
Nationality.create(:code=>"KIR", :name=>"KIRIBATI")
Nationality.create(:code=>"PRK", :name=>"KOREA, D.P.R.O.")
Nationality.create(:code=>"KOR", :name=>"KOREA, REPUBLIC OF")
Nationality.create(:code=>"KWT", :name=>"KUWAIT")
Nationality.create(:code=>"KGZ", :name=>"KYRGYZSTAN")
Nationality.create(:code=>"LAO", :name=>"LAOS ")
Nationality.create(:code=>"LVA", :name=>"LATVIA")
Nationality.create(:code=>"LBN", :name=>"LEBANON")
Nationality.create(:code=>"LSO", :name=>"LESOTHO")
Nationality.create(:code=>"LBR", :name=>"LIBERIA")
Nationality.create(:code=>"LBY", :name=>"LIBYAN ARAB JAMAHIRIYA")
Nationality.create(:code=>"LIE", :name=>"LIECHTENSTEIN")
Nationality.create(:code=>"LTU", :name=>"LITHUANIA")
Nationality.create(:code=>"LUX", :name=>"LUXEMBOURG")
Nationality.create(:code=>"MAC", :name=>"MACAU")
Nationality.create(:code=>"MKD", :name=>"MACEDONIA")
Nationality.create(:code=>"MDG", :name=>"MADAGASCAR")
Nationality.create(:code=>"MWI", :name=>"MALAWI")
Nationality.create(:code=>"MYS", :name=>"MALAYSIA")
Nationality.create(:code=>"MDV", :name=>"MALDIVES")
Nationality.create(:code=>"MLI", :name=>"MALI")
Nationality.create(:code=>"MLT", :name=>"MALTA")
Nationality.create(:code=>"MHL", :name=>"MARSHALL ISLANDS")
Nationality.create(:code=>"MTQ", :name=>"MARTINIQUE")
Nationality.create(:code=>"MRT", :name=>"MAURITANIA")
Nationality.create(:code=>"MUS", :name=>"MAURITIUS")
Nationality.create(:code=>"MYT", :name=>"MAYOTTE")
Nationality.create(:code=>"MEX", :name=>"MEXICO")
Nationality.create(:code=>"FSM", :name=>"MICRONESIA, FEDERATED STATES OF")
Nationality.create(:code=>"MDA", :name=>"MOLDOVA, REPUBLIC OF")
Nationality.create(:code=>"MCO", :name=>"MONACO")
Nationality.create(:code=>"MNG", :name=>"MONGOLIA")
Nationality.create(:code=>"MNE", :name=>"MONTENEGRO")
Nationality.create(:code=>"MSR", :name=>"MONTSERRAT")
Nationality.create(:code=>"MAR", :name=>"MOROCCO")
Nationality.create(:code=>"MOZ", :name=>"MOZAMBIQUE")
Nationality.create(:code=>"MMR", :name=>"MYANMAR (Burma) ")
Nationality.create(:code=>"NAM", :name=>"NAMIBIA")
Nationality.create(:code=>"NRU", :name=>"NAURU")
Nationality.create(:code=>"NPL", :name=>"NEPAL")
Nationality.create(:code=>"NLD", :name=>"NETHERLANDS")
Nationality.create(:code=>"ANT", :name=>"NETHERLANDS ANTILLES")
Nationality.create(:code=>"NCL", :name=>"NEW CALEDONIA")
Nationality.create(:code=>"NZL", :name=>"NEW ZEALAND")
Nationality.create(:code=>"NIC", :name=>"NICARAGUA")
Nationality.create(:code=>"NER", :name=>"NIGER")
Nationality.create(:code=>"NGA", :name=>"NIGERIA")
Nationality.create(:code=>"NIU", :name=>"NIUE")
Nationality.create(:code=>"NFK", :name=>"NORFOLK ISLAND")
Nationality.create(:code=>"MNP", :name=>"NORTHERN MARIANA ISLANDS")
Nationality.create(:code=>"NOR", :name=>"NORWAY")
Nationality.create(:code=>"OMN", :name=>"OMAN")
Nationality.create(:code=>"PAK", :name=>"PAKISTAN")
Nationality.create(:code=>"PLW", :name=>"PALAU")
Nationality.create(:code=>"PAN", :name=>"PANAMA")
Nationality.create(:code=>"PNG", :name=>"PAPUA NEW GUINEA")
Nationality.create(:code=>"PRY", :name=>"PARAGUAY")
Nationality.create(:code=>"PER", :name=>"PERU")
Nationality.create(:code=>"PHL", :name=>"PHILIPPINES")
Nationality.create(:code=>"PCN", :name=>"PITCAIRN")
Nationality.create(:code=>"POL", :name=>"POLAND")
Nationality.create(:code=>"PRT", :name=>"PORTUGAL")
Nationality.create(:code=>"PRI", :name=>"PUERTO RICO")
Nationality.create(:code=>"QAT", :name=>"QATAR")
Nationality.create(:code=>"REU", :name=>"REUNION")
Nationality.create(:code=>"ROM", :name=>"ROMANIA")
Nationality.create(:code=>"RUS", :name=>"RUSSIAN FEDERATION")
Nationality.create(:code=>"RWA", :name=>"RWANDA")
Nationality.create(:code=>"KNA", :name=>"SAINT KITTS AND NEVIS")
Nationality.create(:code=>"LCA", :name=>"SAINT LUCIA")
Nationality.create(:code=>"VCT", :name=>"SAINT VINCENT AND THE GRENADINES")
Nationality.create(:code=>"WSM", :name=>"SAMOA")
Nationality.create(:code=>"SMR", :name=>"SAN MARINO")
Nationality.create(:code=>"STP", :name=>"SAO TOME AND PRINCIPE")
Nationality.create(:code=>"SAU", :name=>"SAUDI ARABIA")
Nationality.create(:code=>"SEN", :name=>"SENEGAL")
Nationality.create(:code=>"SRB", :name=>"SERBIA")
Nationality.create(:code=>"SYC", :name=>"SEYCHELLES")
Nationality.create(:code=>"SLE", :name=>"SIERRA LEONE")
Nationality.create(:code=>"SGP", :name=>"SINGAPORE")
Nationality.create(:code=>"SVK", :name=>"SLOVAKIA (Slovak Republic)")
Nationality.create(:code=>"SVN", :name=>"SLOVENIA")
Nationality.create(:code=>"SLB", :name=>"SOLOMON ISLANDS")
Nationality.create(:code=>"SOM", :name=>"SOMALIA")
Nationality.create(:code=>"ZAF", :name=>"SOUTH AFRICA")
Nationality.create(:code=>"SSD", :name=>"SOUTH SUDAN")
Nationality.create(:code=>"SGS", :name=>"SOUTH GEORGIA AND SOUTH S.S.")
Nationality.create(:code=>"ESP", :name=>"SPAIN")
Nationality.create(:code=>"LKA", :name=>"SRI LANKA")
Nationality.create(:code=>"SHN", :name=>"ST. HELENA")
Nationality.create(:code=>"SPM", :name=>"ST. PIERRE AND MIQUELON")
Nationality.create(:code=>"SDN", :name=>"SUDAN")
Nationality.create(:code=>"SUR", :name=>"SURINAME")
Nationality.create(:code=>"SJM", :name=>"SVALBARD AND JAN MAYEN ISLANDS")
Nationality.create(:code=>"SWZ", :name=>"SWAZILAND")
Nationality.create(:code=>"SWE", :name=>"SWEDEN")
Nationality.create(:code=>"CHE", :name=>"SWITZERLAND")
Nationality.create(:code=>"SYR", :name=>"SYRIAN ARAB REPUBLIC")
Nationality.create(:code=>"TWN", :name=>"TAIWAN, PROVINCE OF CHINA")
Nationality.create(:code=>"TJK", :name=>"TAJIKISTAN")
Nationality.create(:code=>"TZA", :name=>"TANZANIA, UNITED REPUBLIC OF")
Nationality.create(:code=>"THA", :name=>"THAILAND")
Nationality.create(:code=>"TGO", :name=>"TOGO")
Nationality.create(:code=>"TKL", :name=>"TOKELAU")
Nationality.create(:code=>"TON", :name=>"TONGA")
Nationality.create(:code=>"TTO", :name=>"TRINIDAD AND TOBAGO")
Nationality.create(:code=>"TUN", :name=>"TUNISIA")
Nationality.create(:code=>"TUR", :name=>"TURKEY")
Nationality.create(:code=>"TKM", :name=>"TURKMENISTAN")
Nationality.create(:code=>"TCA", :name=>"TURKS AND CAICOS ISLANDS")
Nationality.create(:code=>"TUV", :name=>"TUVALU")
Nationality.create(:code=>"UGA", :name=>"UGANDA")
Nationality.create(:code=>"UKR", :name=>"UKRAINE")
Nationality.create(:code=>"ARE", :name=>"UNITED ARAB EMIRATES")
Nationality.create(:code=>"GBR", :name=>"UNITED KINGDOM")
Nationality.create(:code=>"USA", :name=>"UNITED STATES")
Nationality.create(:code=>"UMI", :name=>"U.S. MINOR ISLANDS")
Nationality.create(:code=>"URY", :name=>"URUGUAY")
Nationality.create(:code=>"UZB", :name=>"UZBEKISTAN")
Nationality.create(:code=>"VUT", :name=>"VANUATU")
Nationality.create(:code=>"VEN", :name=>"VENEZUELA")
Nationality.create(:code=>"VNM", :name=>"VIET NAM")
Nationality.create(:code=>"VGB", :name=>"VIRGIN ISLANDS (BRITISH)")
Nationality.create(:code=>"VIR", :name=>"VIRGIN ISLANDS (U.S.)")
Nationality.create(:code=>"WLF", :name=>"WALLIS AND FUTUNA ISLANDS")
Nationality.create(:code=>"ESH", :name=>"WESTERN SAHARA")
Nationality.create(:code=>"YEM", :name=>"YEMEN")
Nationality.create(:code=>"ZMB", :name=>"ZAMBIA")
Nationality.create(:code=>"ZWE ", :name=>"ZIMBABWE")
